version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/order-service.jar order-service.jar
artifacts:
  files:
    - order-service.jar
    - .ebextensions/**/*