version: 0.2

phases:
  pre_build:
    commands:      
      - echo Logging in to Amazon ECR...
      - mvn clean package  
  build:
    commands:
      - echo Build startedd on `date`   
  post_build:
    commands:
      - echo Build completed on `date`
 
artifacts:
  files:
   - target/order-service.jar